---
- name: Copy desktop-background to host
  tags: [config]
  become: true
  ansible.builtin.copy:
      src: '{{ client_desktop_bg_src }}'
      dest: /usr/share/backgrounds/{{ client_desktop_bg_src | basename }}
      mode: '0644'
      owner: '{{ customize_user }}'

- name: Set desktop-background
  become: true
  become_user: "{{ customize_user }}"
  ansible.builtin.shell: | 
    dbus-launch dconf load /org/mate/desktop/ << EOF 
    [background]
    picture-filename='/usr/share/backgrounds/{{ client_desktop_bg_src | basename }}'
    EOF
  environment:
    DISPLAY: ":0"